edition = "2024"
unstable_features = true

group_imports = "StdExternalCrate"
imports_granularity = "Module"

reorder_impl_items = true

use_field_init_shorthand = true

hex_literal_case = "Upper"

overflow_delimited_expr = true
single_line_let_else_max_width = 80
